name: UI Tests

on:
  push:
    branches:
      - main

jobs:
  # TODO: Add accessibility, interaction and maybe userflow testing (maybe these should be in tests.yml)
  chromatic:
    name: Visual
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for changed UI files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ui:
              - 'packages/web/src/components/ui/**/*.tsx'
              - 'packages/web/.storybook/*'
              - 'packages/web/src/global.css'
              - 'packages/web/tailwind.config.js'
              - 'packages/web/package.json'
              - '.github/workflows/ui_tests.yml'
      - name: Set up node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build Storybook
        run: yarn workspace @syncbase/web build-storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          skip: ${{ steps.changes.outputs.ui == 'false' }}
          projectToken: 64e3a9911647
          workingDir: packages/web
          storybookBuildDir: storybook-static
